-- AlterTable
ALTER TABLE `EPN_USUARIO` MODIFY `nombre` VARCHAR(191);

-- CreateTable
CREATE TABLE `Mascota` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(191) NOT NULL,
    `usuarioId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Mascota` ADD CONSTRAINT `Mascota_usuarioId_fkey` FOREIGN KEY (`usuarioId`) REFERENCES `EPN_USUARIO`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
